// src/pages/ForgotPassword.vue
<template>
  <q-container>
    <div class="mt-8 flex flex-col items-center">
      <template v-if="!reseted">
        <q-avatar class="ma-1" color="secondary">
          <LockOutlinedIcon />
        </q-avatar>
        <h1 class="text-h5">Reset your Password</h1>
      </template>
      <div v-else class="mt-1 flex flex-col items-center text-center">
        <q-avatar class="ma-1" color="secondary">
          <LockOutlinedIcon />
        </q-avatar>

        <h3 class="text-subtitle1">
          You will receive a password recovery link at your email address in a
          few minutes. Please check your mailbox
        </h3>
      </div>

      <q-form class="mt-1" @submit="resetPassword" noValidate>
        <template v-if="!reseted">
          <q-input
            margin="normal"
            required
            fullWidth
            id="email"
            label="Email Address"
            name="email"
            autoComplete="email"
            autoFocus
            v-model="email"
            :rules="[createRuleEmail()]"
          />
          <q-btn type="submit" fullWidth variant="contained" class="mt-3">
            Reset Password
          </q-btn>

          <LoginWithSocial />
        </template>

        <q-container class="mt-5">
          <Grid item xs>
            <Link href="/sign-in" variant="body2">
              Already have login and password? Sign In
            </Link>
          </Grid>
          <Grid item>
            <Link href="/sign-up" variant="body2">
              {"Don't have an account? Sign Up"}
            </Link>
          </Grid>
        </q-container>
      </q-form>
    </div>
    <Copyright class="mt-8 mb-4" />
  </q-container>
</template>

<script lang="ts" setup>
import { getAuth, sendPasswordResetEmail, AuthError } from "@firebase/auth"
import { useQuasar } from "quasar"
import { app } from "src/modules/firebase"
import { ref } from "vue"

import { createRuleEmail } from "src/components/sign/validator"

const $q = useQuasar()
const reseted = ref(false)

const email = ref("")

const resetPassword = async (event: FormDataEvent) => {
  const auth = getAuth(app)

  event.preventDefault()

  const data = new FormData(event.currentTarget)

  console.log({
    email: data.get("email")
  })

  try {
    await sendPasswordResetEmail(auth, data.get("email") as string)

    reseted.value = true
  } catch (err) {
    console.log(err)
    const error = err as AuthError
    $q.notify(`Reset password failed: ${error.message}`)
  }
}
</script>

// src/pages/ForgotPassword.tsx
import type { AuthError } from "@firebase/auth"
import { getAuth, sendPasswordResetEmail } from "@firebase/auth"
import LockOutlinedIcon from "@mui/icons-material/LockOutlined"
import MarkEmailReadRoundedIcon from "@mui/icons-material/MarkEmailReadRounded"
import Avatar from "@mui/material/Avatar"
import Box from "@mui/material/Box"
import Button from "@mui/material/Button"
import Container from "@mui/material/Container"
import Grid from "@mui/material/Grid"
import Link from "@mui/material/Link"
import TextField from "@mui/material/TextField"
import Typography from "@mui/material/Typography"
import { useState } from "react"

import { Copyright } from "~/components/sign/Copyright"
import { LoginWithSocial } from "~/components/sign/LoginWithSocial"
import { createSnackbar } from "~/components/sign/createSnackbar"
import { createRuleEmail, validator } from "~/components/sign/validator"
import { app } from "~/modules/firebase"

export function ForgotPassword(): JSX.Element {
  const auth = getAuth(app)
  // connectEmulator(auth, connectAuthEmulator, 9099)

  const { openSnackbar, snackbar } = createSnackbar()

  const [reseted, setReseted] = useState(false)

  const resetPassword = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()

    setShowError(true)

    if (!validation.passed) return

    const data = new FormData(event.currentTarget)

    console.log({
      email: data.get("email")
    })

    try {
      await sendPasswordResetEmail(auth, data.get("email") as string)

      setReseted(true)
    } catch (err) {
      console.log(err)
      const error = err as AuthError
      openSnackbar({
        type: "error",
        message: `Reset password failed: ${error.message}`
      })
    }
  }

  const [email, setEmail] = useState("")

  const [showError, setShowError] = useState(false)

  const validation = validator(
    {
      email
    },
    {
      email: createRuleEmail()
    }
  )

  return (
    <Container component="main" maxWidth="xs">
      <Box
        sx={{
          marginTop: 8,
          display: "flex",
          flexDirection: "column",
          alignItems: "center"
        }}
      >
        {!reseted && (
          <>
            <Avatar sx={{ m: 1, bgcolor: "secondary.main" }}>
              <LockOutlinedIcon />
            </Avatar>
            <Typography component="h1" variant="h5">
              Reset your Password
            </Typography>
          </>
        )}

        {reseted && (
          <Box
            sx={{
              mt: 1,
              display: "flex",
              flexDirection: "column",
              alignItems: "center"
            }}
            className="text-center"
          >
            <Avatar sx={{ m: 1, bgcolor: "secondary.main" }}>
              <MarkEmailReadRoundedIcon />
            </Avatar>

            <Typography variant="subtitle1">
              You will receive a password recovery link at your email address in
              a few minutes. Please check your mailbox
            </Typography>
          </Box>
        )}

        <Box
          component="form"
          onSubmit={resetPassword}
          noValidate
          sx={{ mt: 1 }}
        >
          {!reseted && (
            <>
              <TextField
                margin="normal"
                required
                fullWidth
                id="email"
                label="Email Address"
                name="email"
                autoComplete="email"
                autoFocus
                onChange={(e) => setEmail(e.target.value)}
                error={showError && !!validation.errors.email}
                helperText={validation.errors.email}
              />
              <Button
                type="submit"
                fullWidth
                variant="contained"
                sx={{ mt: 3 }}
              >
                Reset Password
              </Button>

              <LoginWithSocial />
            </>
          )}

          <Grid container sx={{ mt: 5 }}>
            <Grid item xs>
              <Link href="/forgot-password" variant="body2">
                Already have login and password? Sign In
              </Link>
            </Grid>
            <Grid item>
              <Link href="/sign-up" variant="body2">
                {"Don't have an account? Sign Up"}
              </Link>
            </Grid>
          </Grid>
        </Box>
      </Box>

      <Copyright sx={{ mt: 8, mb: 4 }} />

      {snackbar}
    </Container>
  )
}
