// src/pages/SignIn.vue
<template>
  <q-container component="main" maxWidth="xs">
    <div class="mt-8 flex flex-col items-center">
      <q-avatar class="ma-1 bg-secondary">
        <LockOutlinedIcon />
      </q-avatar>
      <h1 class="text-h5">Sign in</h1>
      <q-form @submit="signIn" class="mt-1">
        <q-input
          margin="normal"
          required
          fullWidth
          id="email"
          label="Email Address"
          name="email"
          autoComplete="email"
          autoFocus
          v-model="email"
          :rules="[createRuleEmail()]"
        />
        <q-input
          margin="normal"
          required
          fullWidth
          name="password"
          label="Password"
          type="password"
          id="password"
          autoComplete="current-password"
          v-model="password"
          :rules="[createRulePassword()]"
        />
        <q-checkbox label="Remember me" />

        <q-btn type="submit" fullWidth variant="contained" class="mt-3">
          Sign In
        </q-btn>

        <LoginWithSocial />

        <q-container class="mt-5">
          <Grid item xs>
            <Link href="/forgot-password" variant="body2">
              Forgot password?
            </Link>
          </Grid>
          <Grid item>
            <Link href="/sign-up" variant="body2">
              {"Don't have an account? Sign Up"}
            </Link>
          </Grid>
        </q-container>
      </q-form>
    </div>
    <Copyright class="mt-8 mb-4" />
  </q-container>
</template>

<script lang="ts" setup>
import { getAuth, signInWithEmailAndPassword, AuthError } from "@firebase/auth"
import { useQuasar } from "quasar"
import { app } from "src/modules/firebase"
import { ref } from "vue"

import {
  createRuleEmail,
  createRulePassword
} from "src/components/sign/validator"

const auth = getAuth(app)

const $q = useQuasar()

const email = ref("")
const password = ref("")

const signIn = async (event: FormDataEvent) => {
  event.preventDefault()

  const data = new FormData(event.currentTarget)

  console.log({
    email: data.get("email"),
    password: data.get("password")
  })

  try {
    const { user } = await signInWithEmailAndPassword(
      auth,
      data.get("email") as string,
      data.get("password") as string
    )

    console.log(user)

    $q.notify(`Logged in as ${user.displayName}`)
  } catch (err) {
    console.log(err)
    const error = err as AuthError
    $q.notify(`Login failed: ${error.message}`)
  }
}
</script>

// src/pages/SignIn.tsx
import type { AuthError } from "@firebase/auth"
import { getAuth, signInWithEmailAndPassword } from "@firebase/auth"
import LockOutlinedIcon from "@mui/icons-material/LockOutlined"
import Avatar from "@mui/material/Avatar"
import Box from "@mui/material/Box"
import Button from "@mui/material/Button"
import Checkbox from "@mui/material/Checkbox"
import Container from "@mui/material/Container"
import FormControlLabel from "@mui/material/FormControlLabel"
import Grid from "@mui/material/Grid"
import Link from "@mui/material/Link"
import TextField from "@mui/material/TextField"
import Typography from "@mui/material/Typography"
import { useState } from "react"

import { Copyright } from "~/components/sign/Copyright"
import { LoginWithSocial } from "~/components/sign/LoginWithSocial"
import { createSnackbar } from "~/components/sign/createSnackbar"
import {
  createRuleEmail,
  createRulePassword,
  validator
} from "~/components/sign/validator"
import { app } from "~/modules/firebase"

export function SignIn(): JSX.Element {
  const auth = getAuth(app)
  // connectEmulator(auth, connectAuthEmulator, 9099)

  const { openSnackbar, snackbar } = createSnackbar()

  const signIn = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()

    setShowError(true)

    if (!validation.passed) return

    const data = new FormData(event.currentTarget)

    console.log({
      email: data.get("email"),
      password: data.get("password")
    })

    try {
      const { user } = await signInWithEmailAndPassword(
        auth,
        data.get("email") as string,
        data.get("password") as string
      )

      console.log(user)

      openSnackbar({
        type: "success",
        message: `Logged in as ${user.displayName}`
      })
    } catch (err) {
      console.log(err)
      const error = err as AuthError
      openSnackbar({
        type: "error",
        message: `Login failed: ${error.message}`
      })
    }
  }

  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")

  const [showError, setShowError] = useState(false)

  const validation = validator(
    {
      email,
      password
    },
    {
      email: createRuleEmail(),
      password: createRulePassword()
    }
  )

  return (
    <Container component="main" maxWidth="xs">
      <Box
        maxWidth="xs"
        sx={{
          marginTop: 8,
          display: "flex",
          flexDirection: "column",
          alignItems: "center"
        }}
      >
        <Avatar sx={{ m: 1, bgcolor: "secondary.main" }}>
          <LockOutlinedIcon />
        </Avatar>
        <Typography component="h1" variant="h5">
          Sign in
        </Typography>
        <Box component="form" onSubmit={signIn} noValidate sx={{ mt: 1 }}>
          <TextField
            margin="normal"
            required
            fullWidth
            id="email"
            label="Email Address"
            name="email"
            autoComplete="email"
            autoFocus
            onChange={(e) => setEmail(e.target.value)}
            error={showError && !!validation.errors.email}
            helperText={validation.errors.email}
          />
          <TextField
            margin="normal"
            required
            fullWidth
            name="password"
            label="Password"
            type="password"
            id="password"
            autoComplete="current-password"
            onChange={(e) => setPassword(e.target.value)}
            error={showError && !!validation.errors.password}
            helperText={validation.errors.password}
          />
          <FormControlLabel
            control={<Checkbox value="remember" color="primary" />}
            label="Remember me"
          />
          <Button type="submit" fullWidth variant="contained" sx={{ mt: 3 }}>
            Sign In
          </Button>

          <LoginWithSocial />

          <Grid container sx={{ mt: 5 }}>
            <Grid item xs>
              <Link href="#" variant="body2">
                Forgot password?
              </Link>
            </Grid>
            <Grid item>
              <Link href="/sign-up" variant="body2">
                {"Don't have an account? Sign Up"}
              </Link>
            </Grid>
          </Grid>
        </Box>
      </Box>
      <Copyright sx={{ mt: 8, mb: 4 }} />

      {snackbar}
    </Container>
  )
}
