// src/pages/Sketch.tsx
import "./Index.scss"

import { doc, getDoc, getFirestore } from "@firebase/firestore"
import { Icon } from "@iconify/react"
import type { editor } from "monaco-editor"
import { useEffect, useRef, useState } from "react"
import { useParams } from "react-router"

import { EditorFile } from "~/components/sketch/EditorFile"
import { Preview } from "~/components/sketch/Preview"
import { SideBar } from "~/components/sketch/SideBar"
import { ToolBar } from "~/components/sketch/ToolBar"
import { app } from "~/modules/firebase"
import { useToast } from "~/plugins/toast"
import sketchDefault from "~/templates/sketch-default"
import { useCreateSketch } from "~/useActions/editor-actions"

export function Sketch() {
  const editorRef = useRef<editor.ICodeEditor | editor.IStandaloneCodeEditor>()
  const params = useParams()
  const { addToast } = useToast()

  const [loading, setLoading] = useState(true)
  const createSketch = useCreateSketch()

  useEffect(() => {
    const db = getFirestore(app)

    if (params.userId && params.sketchId) {
      const docRef = doc(
        db,
        "users",
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
        params.userId!,
        "sketches",
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
        params.sketchId!
      )
      // eslint-disable-next-line promise/catch-or-return
      getDoc(docRef)
        // eslint-disable-next-line promise/always-return
        .then((snap) => {
          // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
          const { fs: template, name } = snap.data()!

          createSketch({
            id: snap.id,
            name,
            template
          })
        })
        .catch(() => {
          addToast("Sketch not found")
        })
        .finally(() => setLoading(false))
    } else {
      createSketch({
        template: sketchDefault
      })

      setLoading(false)
    }
  }, [])

  if (loading) {
    return (
      <div className="absolute w-full h-full flex items-center justify-center text-sm">
        <div className="text-center">
          <Icon icon="line-md:loading-loop" className="w-45px h-45px" />
          <br />
          Fetching Sketch...
        </div>
      </div>
    )
  }

  return (
    <div className="page">
      <ToolBar />

      <div className="flex h-full">
        <SideBar editorRef={editorRef} />

        <div className="flex relative w-full flex-1">
          <div className="w-full h-full flex">
            <EditorFile editorRef={editorRef} />
            <Preview editorRef={editorRef} />
          </div>
        </div>
      </div>
    </div>
  )
}

// src/pages/Sketch.vue
<template>
  <q-page
    v-if="loading"
    class="absolute w-full h-full flex items-center justify-center text-sm"
  >
    <div class="text-center">
      <q-spinner-hourglass color="primary" size="2em" />
      <br />
      Fetching Sketch...
    </div>
  </q-page>

  <q-page v-else class="flex column">
    <ToolBar  />

    <div class="flex h-full flex-1">
      <SideBar />

      <div class="flex relative w-full flex-1">
        <div class="w-full h-full flex">
          <EditorFile />
          <Preview />
        </div>
      </div>
    </div>
  </q-page>
</template>

<script lang="ts" setup>
import { doc, getDoc, getFirestore } from "@firebase/firestore"
import EditorFile from "components/sketch/EditorFile.vue"
import Preview from "components/sketch/Preview.vue"
import SideBar from "components/sketch/SideBar.vue"
import ToolBar from "components/sketch/ToolBar.vue"
import { useQuasar } from "quasar"
import { app } from "src/modules/firebase"
import { useEditorStore } from "src/stores/editor"
import sketchDefault from "src/templates/sketch-default"
import { ref, watch } from "vue"
import { useRoute } from "vue-router"

const loading = ref(false)

const db = getFirestore(app)

const route = useRoute()
const $q = useQuasar()
const editorStore = useEditorStore()
const { createSketch } = editorStore

watch(() => route.params.userId, loadSketch)
watch(() => route.params.sketchId, loadSketch)
loadSketch()

async function loadSketch() {
   
  loading.value = true

  if (route.params.userId && route.params.sketchId) {
    const docRef = doc(
      db,
      "users",
      route.params.userId as string,
      "sketches",
      route.params.sketchId as string
    )

    try {
      const snap = await getDoc(docRef)

      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
      const { fs: template, name } = snap.data()!

      createSketch({
        id: snap.id,
        name,
        template
      })
    } catch {
      $q.notify("Sketch not found")
    }
  } else {
    createSketch({
      template: sketchDefault
    })
  }

   
  loading.value = false
}
</script>
